### ISSUE TITLE
I can't build an apk

### ISSUE THREAD

**Issue by turbo-hackers** [ArtemSBulgakov/buildozer-action#29]
I try to build it shows these error : 

1)
Build for Android
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

2)
Build for Android
Failed to remove 'http.https://github.com/.extraheader' from the git config

main.yml code is : 
```
name: Build

on: [push, pull_request]

jobs:

  # Build job. Builds app for Android with Buildozer

  build-android:

    name: Build for Android

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v2

      - name: Build with Buildozer

        uses: ArtemSBulgakov/buildozer-action@v1

        id: buildozer

        with:

          workdir: .

          buildozer_version: stable

      - name: Upload artifacts

        uses: actions/upload-artifact@v2

        with:

          name: package

          path: ${{ steps.buildozer.outputs.filename }}
```
Please help me to fix this
