### ISSUE TITLE
Workflow error "No jobs defined in jobs"

### ISSUE THREAD

**Issue by richierh** [ArtemSBulgakov/buildozer-action#7]
I use 

```yaml
name: Build
on: [push, pull_request]

jobs:
# Build job. Builds app for Android with Buildozer
build-android:
  name: Build for Android
  runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        #workdir: .
        buildozer_version: stable

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: ${{ steps.buildozer.outputs.filename }}
```
but not working , when I clicked Actions it goes Failure

**Comment by ArtemSBulgakov** [comment]
Hi, @richierh 

I think you missed indentation. Try to add two spaces before all lines after
```
jobs:
```

**Comment by richierh** [comment]
like what ? I don't get it?

**Comment by ArtemSBulgakov** [comment]
It should work:
```yaml
name: Build
on: [push, pull_request]

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          #workdir: .
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
```
